use Cordys;
CREATE TABLE "BPM_PURGE_STATUS" (
"TASK_NAME" varchar(20),
"TASK_STATUS" varchar(20),
PRIMARY KEY ("TASK_NAME")
);
INSERT INTO BPM_PURGE_STATUS VALUES('getbpminstances','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('deleteactivity','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('deleteinstance','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('deleteinstdata','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('deletebidnum','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('deletebiddate','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('deletebidstring','FALSE');
INSERT INTO BPM_PURGE_STATUS VALUES('trunctemp','FALSE');

