truncate table ICT_INSTANCE_TEMP8;

INSERT INTO ICT_INSTANCE_TEMP8
SELECT PROCESS_INSTANCE.INSTANCE_ID, PROCESS_INSTANCE.PROCESS_NAME,
PROCESS_INSTANCE.ORGANIZATION
FROM PROCESS_INSTANCE, PROCESS_ACTIVITY
WHERE PROCESS_INSTANCE.INSTANCE_ID = PROCESS_ACTIVITY.INSTANCE_ID
AND PROCESS_INSTANCE.STATUS IN ('COMPLETE','Completed')
AND (PROCESS_INSTANCE.END_TIME / 1000) < (DATEDIFF(s, '1970-01-01 00:00:00', GETUTCDATE()) - (SELECT ARCHIVE_DELAY FROM BPM_ARCHIVE_DELAY WHERE PROCESS_INSTANCE.PROCESS_NAME = BPM_ARCHIVE_DELAY.BPM_NAME))
GROUP BY PROCESS_INSTANCE.PROCESS_NAME, PROCESS_INSTANCE.INSTANCE_ID,
PROCESS_INSTANCE.ORGANIZATION;

delete PROCESS_ACTIVITY from PROCESS_ACTIVITY INNER JOIN ICT_INSTANCE_TEMP8 on ICT_INSTANCE_TEMP8.INSTANCE_ID=PROCESS_ACTIVITY.INSTANCE_ID;

delete PROCESS_INSTANCE from PROCESS_INSTANCE INNER JOIN ICT_INSTANCE_TEMP8 on ICT_INSTANCE_TEMP8.INSTANCE_ID=PROCESS_INSTANCE.INSTANCE_ID;

delete PROCESS_INSTANCE_DATA from PROCESS_INSTANCE_DATA INNER JOIN ICT_INSTANCE_TEMP8 on ICT_INSTANCE_TEMP8.INSTANCE_ID=PROCESS_INSTANCE_DATA.INSTANCE_ID;

delete BUSINESS_IDENTIFIER_NUMERIC from BUSINESS_IDENTIFIER_NUMERIC INNER JOIN ICT_INSTANCE_TEMP8 on ICT_INSTANCE_TEMP8.INSTANCE_ID=BUSINESS_IDENTIFIER_NUMERIC.INSTANCE_ID;

delete BUSINESS_IDENTIFIER_DATE from BUSINESS_IDENTIFIER_DATE INNER JOIN ICT_INSTANCE_TEMP8 on ICT_INSTANCE_TEMP8.INSTANCE_ID=BUSINESS_IDENTIFIER_DATE.INSTANCE_ID where;

delete BUSINESS_IDENTIFIER_STRING from BUSINESS_IDENTIFIER_STRING INNER JOIN ICT_INSTANCE_TEMP8 on ICT_INSTANCE_TEMP8.INSTANCE_ID=BUSINESS_IDENTIFIER_STRING.INSTANCE_ID where;

truncate table ICT_INSTANCE_TEMP8;
